### ISSUE TITLE
Offer ROM for download

### ISSUE THREAD

**Issue by svendahlstrand** [svendahlstrand/10-print-game-boy#3]

**Comment by tobiasvl** [comment]
Not sure how you plan on doing this, but I'd suggest just making a [GitHub Release](https://help.github.com/articles/creating-releases/), which can be accompanied by a binary.

**Comment by svendahlstrand** [comment]
Yes, that was the plan, and I just pushed the button for `0x01`. I'm making a SemVer exception for Game Boy releases so I can use the mask ROM version number in the binary. 😄

**Comment by svendahlstrand** [comment]
Link added to README in 366f7ca76ce2bd549dd7cb74eb931b75f9eed759.
